// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImgToPdf() {
  return window['go']['main']['App']['ImgToPdf']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OptimizeFile() {
  return window['go']['main']['App']['OptimizeFile']();
}
