// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImgToPdf() {
  return window['go']['main']['App']['ImgToPdf']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenSinglePdf() {
  return window['go']['main']['App']['OpenSinglePdf']();
}

export function OptimizeFile() {
  return window['go']['main']['App']['OptimizeFile']();
}

export function PrintArr(arg1) {
  return window['go']['main']['App']['PrintArr'](arg1);
}

export function PrintString(arg1) {
  return window['go']['main']['App']['PrintString'](arg1);
}

export function PrintT(arg1) {
  return window['go']['main']['App']['PrintT'](arg1);
}

export function RemovePages(arg1, arg2) {
  return window['go']['main']['App']['RemovePages'](arg1, arg2);
}
