// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ImgToPdf():Promise<string>;

export function MergePdf():Promise<string>;

export function MoovePdfPage(arg1:string,arg2:number):Promise<string>;

export function OpenSinglePdf():Promise<string>;

export function OpenSinglePdfFromPath(arg1:string):Promise<string>;

export function OptimizePdf():Promise<string>;

export function PrintAny(arg1:any):Promise<void>;

export function PrintArr(arg1:Array<any>):Promise<void>;

export function PrintString(arg1:string):Promise<void>;

export function RemovePages(arg1:Array<number>,arg2:string):Promise<string>;

export function ReorderPdf(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveModifiedPDF(arg1:string):Promise<void>;
