// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['Application']['App']['Greet'](arg1);
}

export function ImgToPdf() {
  return window['go']['Application']['App']['ImgToPdf']();
}

export function MergePdf() {
  return window['go']['Application']['App']['MergePdf']();
}

export function OpenSinglePdf() {
  return window['go']['Application']['App']['OpenSinglePdf']();
}

export function OptimizePdf() {
  return window['go']['Application']['App']['OptimizePdf']();
}

export function PrintAny(arg1) {
  return window['go']['Application']['App']['PrintAny'](arg1);
}

export function PrintArr(arg1) {
  return window['go']['Application']['App']['PrintArr'](arg1);
}

export function PrintString(arg1) {
  return window['go']['Application']['App']['PrintString'](arg1);
}

export function RemovePages(arg1, arg2) {
  return window['go']['Application']['App']['RemovePages'](arg1, arg2);
}

export function SaveModifiedPDF(arg1) {
  return window['go']['Application']['App']['SaveModifiedPDF'](arg1);
}
